# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [ main, '*staging*', 'rapid-v1.x' ]

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

env:
  FORCE_COLOR: 2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo "::remove-matcher owner=eslint-compact::"
        echo "::remove-matcher owner=eslint-stylish::"

    - name: Checkout 📥
      uses: actions/checkout@v4

    - name: Use Node.js 18 ⚙️
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install 🎯
      run: npm install

    - name: Run 🏃
      run: npm run all

    - name: Test 🧪
      run: npm run test

    - name: Configure AWS credentials 🔐
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_RAPID_DEPLOY_ROLE_ARN }}
        role-duration-seconds: 900 # the ttl of the session, in seconds.
        aws-region: us-west-2

    - name: Setup environment vars 📋
      id: vars
      run: |
        echo "yyyymmdd=$(date +'%Y%m%d')"                           >> "$GITHUB_ENV"
        echo "revision=$(git rev-parse --short ${{ github.sha }})"  >> "$GITHUB_ENV"
        echo "distpath=${yyyymmdd}-${revision}"                     >> "$GITHUB_ENV"

    - name: Predeploy index.html 🔨
      run: node scripts/predeploy.js
      env:
        YYYYMMDD: ${{ env.yyyymmdd }}
        REVISION: ${{ env.revision }}
        DISTPATH: ${{ env.distpath }}

    - name: Copy build to S3 📤
      run: |
        aws s3 cp dist             s3://world.ai.rapid/rapid/${{ env.distpath }}  --no-progress --recursive
        aws s3 cp dist/index.html  s3://world.ai.rapid/canary                     --no-progress

    - name: Deployment complete! 🚀
      run: |
        echo "Your build is here: https://rapideditor.org/rapid/${{ env.distpath }}/index.html and https://rapideditor.org/canary"